### ISSUE TITLE
Chrome on Lollipop picks low res icon

### ISSUE THREAD

**Issue by fchristant** [RealFaviconGenerator/realfavicongenerator#131]
hi there,

This is more of a question, possibly not an issue in your service. At my website:

http://www.jungledragon.com/

I have used your service, and included this output in the HTML header:

```
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/android-chrome-manifest.json">
```

All files are deployed in the root of the website, and the links work. Still, when using Chrome (v39) on Lollipop, on a Nexus 7 (2013 model), when adding my website to the homescreen, I get this very crappy low-res icon. 

I was wondering if I'm doing anything wrong?

**Comment by phbernard** [comment]
Hi Ferdy,

You did nothing wrong, else the icons wouldn't work at all. Unfortunately, some browsers, and apparently Android Chrome among them, can be a bit lunatic when choosing the icon. I also have a Nexus 7 with Lollipop and Chrome 39. When running the <a href="http://realfavicongenerator.net/favicon_compatibility_test">compatibility test</a>, I could see that Chrome picked two icons:
- The 192x192 icon (highest resolution)
- The 72x72 icon. Not great, but I guess this still fits the screen well. Not the bad result your observed.

You can view the <a href="http://realfavicongenerator.net/favicon_compatibility">compatibility results</a>, look for Nexus 7.

This proves one thing: you cannot predict with a 100% accuracy what Chrome will produce. I suggest you to run the <a href="http://realfavicongenerator.net/favicon_compatibility_test">compatibility test</a> too, just for the sake of trying several "Add to home screen" from different sites. That might confirm the hypothesis.

I even didn't consider the option for this case, but a bug should be filled for Android Chrome. Especially if it takes very low res icon. I wait for your feedback and I'll proceed.

**Comment by fchristant** [comment]
![jd](https://cloud.githubusercontent.com/assets/228781/6007854/9c789f6a-ab1d-11e4-9bee-350384486bf7.png)

Thank you very much for the feedback, I did not know about that compatibility table, thanks! I've attached a screenshot of the issue. It is kind of hard to demonstrate as the issue is only annoying on a high density screen, but the main issue that native icons look pinpoint sharp as per the density, whilst my web site app added to the homescreen looks blurry, really sticking out like a sore thumb.

I tried to take the compatibility test but I don't understand the answers I can select from.

**Comment by phbernard** [comment]
Ok I get it.

There are two things you can try:
- Edit `android-chrome-manifets.json` (one of the file generated by RFG) and remove all icon declarations but the 192x192 one. Android Chrome will have to use it instead of a low-resolution icon.
- In the HTML code, remove the manifest declaration (`<link rel="manifest" href="/manifest.json">`). This will force Android Chrome to use the 192x192 PNG icon, declared elsewhere in the HTML code.

What you might observe:
- The result is better. If so, it means Chrome fails at picking the right picture. Then we will submit a bug to the Chromium team with screenshots.
- Nothing changes, the home screen icon is still disappointing. If so, it means Chrome is not that smart at processing the icon. I'm not sure a bug report is relevant here, as the "icon quality" is a subjective topic. To be honest, in your screenshot above, your icon looks as good as the "Browser" and "Chromecast" ones to me.

About the compatibility test: the goal of the test is to understand which icon is used in a situation or another. Each "test" is a page you are supposed to bookmark and/or add to home screen (of course, it depends on the platform you're testing). Then, you need to report what you see.

In the example above (Windows + Chrome), I report that the tab icon is the 16x16 PNG icons (well, the "green and yellow" icon).

![image](https://cloud.githubusercontent.com/assets/423852/6037899/a7698fce-ac58-11e4-9919-fc2da06998fa.png)

Being colorblind is a clear drawback when running this test :)

**Comment by fchristant** [comment]
Thank you, I understand the working of the test now. When running it on the Nexus 7 (2013), Android 5.02, Chrome 39, it picks the grey/green 96 x 96 px as a home screen icon, which confirms the problem.

Unfortunately, both actions you suggest don't make any difference. Limit the manifest to only the 192px icon or removing the manifest altogether have the same result as before. 

I know the screenshot doesn't show the difference well, but on a high density screen it really sticks out. For completeness sake, this is my updated declaration:

```
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
```

**Comment by phbernard** [comment]
Thank you for checking all this.

I think Chrome is right when it picks the 96x96 icon. In your screenshot above, the icon is actually 96x96. Chrome tries to take the exact same size in order to use it as is, without scaling it, which is a good thing.

The fact that the 192x192 icon gives the same substandard quality confirms this hypothesis: whatever the (high) definition of the picture, Chrome cannot produce a perfect result.

I'm afraid RFG can't do anything more: even if with the "192x192" hack, the result is the same. Plus <a href="http://realfavicongenerator.net/blog/android-chrome-and-its-favicon/">Android Chrome won't take anything above 192x192</a> so the "even higher res pic" route is hopeless.

I added JungleDragon to the home screen of my own Nexus 7 running Lollipop (with your 192x192 hack still active; no low res icons):

![image](https://cloud.githubusercontent.com/assets/423852/6039785/9a001dfa-ac6a-11e4-9247-580acd9c8112.png)

On my screen, the icon is perfect. The resolution is lower on my screen (this is a first gen Nexus 7 if I'm right). I don't know what to think about this result but at least Android can produce a decent result.

**Comment by fchristant** [comment]
It definitely looks decent on your screen, not so much on mine. I just did some more extreme testing, in the HTML I removed everything except the 192px file (I did leave the files in the web root), and still it doesn't pick it up, going for a low res icon still.

That means it's time to give up, it just can't be done it seems. Thank you for all the help though, and your service has definitely helped for almost all other situations.

**Comment by phbernard** [comment]
Thanks!

I also feel it's a bit helpless now... sorry we couldn't get rid of this :-/

The only way to go is to submit a bug to the Chrome team.

**Comment by fchristant** [comment]
It's ok, really, it's just me obsessing over getting from 98% to a 100%.

**Comment by phbernard** [comment]
Same here :)

I tried to fill an issue but realized I don't have enough elements to fill it properly. Next time!

**Comment by fchristant** [comment]
Not enough elements? What do you mean by that?

**Comment by phbernard** [comment]
Well, they ask for a reproducible procedure. I'm not sure of the exact Nexus 7 model (yours and mine differ for example), I can't join your picture as a reference (it's yours after all), I'm not sure to be able to describe the observe result (the icon is neither great nor really wrong)...

I already filled a minor bug properly a year ago. But it was not fixed yet (https://code.google.com/p/chromium/issues/detail?id=324820). So I prefer to skip my turn here.

**Comment by fchristant** [comment]
Regarding the Nexus 7 model, they are uniquely identified by year. You probably have the 2012 model, I have the 2013 model. That identifies them uniquely already.

You can use my picture, it's fine, it just doesn't show the problem very well. The observed result can be described as it being a low density icon whilst the hardware screen is high density (on the 2013 model). Roughly speaking, you could say that the icon is 96 pixels, yet the space it takes up has 4 times the amount of hardware pixels. Thus, it would require a far higher resolution icon for that icon to look sharp natively on such a high density screen. We offer a higher resolution, yet still Chrome does not pick it up.

That would roughly be the problem description from my end. As a reproducable case, it is fine with me to use the website I mentioned (jungledragon.com).

I hope this helps.
