### ISSUE TITLE
link "sizes" attribute fails validation at W3C

### ISSUE THREAD

**Issue by highcliff** [RealFaviconGenerator/realfavicongenerator#137]
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png" />

The Sizes attribute in the Link reference fails causes the W3C validator at http://validator.w3.org/ to fail with "there is no attribute "sizes"", when using the doctype
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

How can we support Apple's multiple favicons without breaking validation?

**Comment by phbernard** [comment]
That's right, the "XHTML support" is a bit abusive. It adds the final `/` at the end of self-closing markups. This is enough to calm down XHTML editors. However, as you mention, the `sizes` attribute is not part of XHTML.

This will be partly fixed with issue #124: lighter package will have a single markup for iOS, without any `sizes` attribute. But that won't be enough: PNG icons, too, have a `sizes` attribute.

Sounds like this issue will never be really fixed.

**Comment by phbernard** [comment]
I think I should have close this issue some time ago.
