### ISSUE TITLE
Firefox requests ALL icons

### ISSUE THREAD

**Issue by sebestindragos** [RealFaviconGenerator/realfavicongenerator#145]
It seems that firefox downloads all the icons declared with meta tags.
Chrome and IE seem to work just fine.

**Comment by phbernard** [comment]
That's right. Well done for spotting this one, not easy to find out!

This is part of <a href="http://realfavicongenerator.net/faq#troubleshootings">RFG's troubleshootings</a>. I take this issue into account when crafting the next version of the code created by RFG. For example, the old 160x160 icon for Opera Speed Dial is not generated anymore.

I contributed several times to the corresponding <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=751712">Firefox bug</a>. Unfortunately, this is apparently not a priority for the FF team :-/ If you have a few minutes, I suggest you to upvote it, or even comment it if you think you have additional material. It might be a way to put this issue at the top of the pile.

I close the issue because I think RFG does everything it can do to cope with this bug, but feel free to continue talking here or even re-open the issue if you have a workaround of some kind to propose.
