### ISSUE TITLE
MS large tiles apparently add too much padding

### ISSUE THREAD

**Issue by dandv** [RealFaviconGenerator/realfavicongenerator#175]
I've uploaded an [1024x1024 icon](https://github.com/iDoRecall/media/blob/master/logo/iDR_logo_1024x1024_dark_on_transparent-Facebook_app_icon.png) and the `mstile-310x310.png` scaled the image to 260px width, with the rest being padding:

![image](https://cloud.githubusercontent.com/assets/33569/8452232/e4270aa0-1f9d-11e5-9d9b-c506bcbc0989.png)

I don't have a Windows 8 at hand (so thanks for RFG!), but I wonder if less padding would allow for a crisper tile icon. The other MS tile icons also shrink the icon apparently too much:
- mstile-150x150.png
- mstile-310x150.png
- mstile-70x70.png

But not `mstile-144x144.png` !

**Comment by phbernard** [comment]
Thank you for reporting.

There are two (bad) reasons for this behavior:
- Differences between Windows 8.0 and 8.1: While W8.1 allows full size tile picture (no padding at all), this is not the case of W8. In W8, IE automatically adds padding around the 144x144 tile picture and applies the background color. So this raises questions: do you want to have two distinct designs for 8.0 and 8.1? Or forget about 8.0? Instead, RFG adds a somehow artificial padding around W8.1 tiles (150x150, 310x150 and 70x70) to simulate W8.0 behavior. This is why you observe a difference between the 144x144 and the other ones.
- A rectangular tile picture? Really? The 310x150 is the only rectangular picture in the favicon universe. All the other platforms (iOS, Android, Coast by Opera, Yandex Browser... all!) only have square pictures. Suddenly, you have to think about a rectangular design for one single picture for one single platform.

These are bad reasons because it is possible to offer the current solution as a valuable default and add options to allow a per-platform and per-shape design. This is the topic of #16.
