### ISSUE TITLE
Versioned favicon.ico causes checker warning

### ISSUE THREAD

**Issue by jacksonj04** [RealFaviconGenerator/realfavicongenerator#191]
When enabling versioning of assets, the output includes a generated `<link rel="shortcut icon" href="favicon.ico?v=foo">` line, which subsequently trips up the checker. Either this line shouldn't be generated (which I would assume is probably the best thing, even if you do run into caching issues most browsers won't care), or the validator should be happy with the `shortcut icon` line as long as it has a version parameter.

**Comment by phbernard** [comment]
That's right, the checker and the generator conflict in this case. I don't see myself removing the link since the user explicitly asked for a version. And I'm confident `favicon.ico` is the top culprit when it comes to caching issue. So the solution would be to ignore link with format `favicon.ico?[anything]=[anything]`, since this is the format produced by RFG.

**Comment by phbernard** [comment]
The checker was rewritten. Now it's less opinionated and such situation leads to a simple "info" (blue) comment. It's not an "error" (red) anymore. And the overall status is "success" (green). I think that clears the issue.
