### ISSUE TITLE
Favicon by RealFaviconGenerator

### ISSUE THREAD

**Issue by gerardeur** [RealFaviconGenerator/realfavicongenerator#226]
Hello,

Favicon by RealFaviconGenerator is not working on my website. Can anybody help me please?

**Comment by gerardeur** [comment]
Here is the link: www.newhairlinestudio.com

**Comment by phbernard** [comment]
Hi,

There are at least two issues:
- You have duplicated content. There are two "blocks" of icons declaration (eg. `apple-touch-icon-57x57.png` appears two times in your source).
- You have a `div` in your `head` section. Some browsers, like Chrome (and all Webkit-based browsers, to my knowledge), consider the header to be closed as soon as they meet this markup. Therefore, the following `link` that declare the icons are just ignored (since they are considered to be in the `body` while this is forbidden). This is why your favicon works in Firefox and not in Chrome.
