### ISSUE TITLE
Favicon checker cannot find favicon markups when they are directly in <html> (not in <head>)

### ISSUE THREAD

**Issue by alekseyg** [RealFaviconGenerator/realfavicongenerator#27]
My application is targeted more towards newer browsers and I mostly test it on the major platforms, so I went with a rather minimal approach to my favicons. I did run it through the checker to see what result I'd get. It obviously (and correctly) gave me warning on all platforms, but one that was unexpected was Windows 8.

Windows 8 allows you to define the icon and color via meta tags, which I have done, but the checker claims that the picture is not declared at all for Windows 8 and the preview for Windows 8 looks bad and doesn't pick up the icon or the color. However, I have tested the web app in Windows 8 and it works exactly as it should.

Here are my meta tags for Windows 8:

``` html
<meta name="msapplication-TileImage" content="/mstile.png">
<meta name="msapplication-TileColor" content="#008dff">
```

Here is the website in question: http://yanteres.com

Perhaps this is not the best way to handle Windows 8/IE 10/IE 11, but it does work and looks nothing like the preview the checker gives, so I would say this is a bug in the checker.

**Comment by phbernard** [comment]
I think this is because your code has no `<head>` section: the `<title>`, `<meta>` and `<link>` markups are directly under `<html>`, before `<body>` starts. The checker looks for the favicon declarations in `<head>`.

At first, I though it was an issue with the HTML. After all, all these markups are supposed to be under `<head>`, right? But I submitted your code to the W3C Validator, just to check... Surprise (for me at least): this is not considered as an error. And I found this on SO: http://stackoverflow.com/questions/5641997/is-it-necessary-to-write-head-body-and-html-tags

I think the checker should be more resilient with such scenario. Maybe print a warning, since I'm not sure all browsers support this. I will do this in a few days.

Thanks for reporting!

**Comment by alekseyg** [comment]
No problem. I generally omit the tags unless I need to use an attribute, such as `lang` in `<html>` and I always have the opening `<body>` tag regardless for IE. It works fine in all browsers that way and is fully valid.

Regarding the error on the checker, I'm guessing this means that the checker doesn't necessarily check if the `<link rel="shortcut icon"...>` and `<link rel="apple-touch-icon"...>` are in the head as the icons would work without, and only checks for the `<meta>` tags for Windows 8?

**Comment by phbernard** [comment]
Fixed and deployed a minute ago. At last. Sorry for this long delay...

A note about W8 support. You say in your first message that you focus mostly on most recent platforms. Beware that [the tiles specs changed since the release of Windows 8.1 and IE11](http://msdn.microsoft.com/en-us/library/ie/dn255024%28v=vs.85%29.aspx). You can declare these new pictures with additional markups in the HTML, but this adds a few hundreds of bytes to the page. Another technique is to use `browserconfig.xml`. Because only W8.1 devices will look for `browserconfig.xml`, this technique does not penalize the other platforms.

You can use RealFaviconGenerator to produce `browserconfig.xml` and the corresponding pictures.

**Comment by alekseyg** [comment]
Sweet. Thanks for the tip.
