### ISSUE TITLE
Issue send file (width, height of file)

### ISSUE THREAD

**Issue by kellerkichel** [RealFaviconGenerator/realfavicongenerator#279]
The website have a bug... its not reading the width or height of send image... following the error at console:
![image](https://cloud.githubusercontent.com/assets/4204423/19039375/0156e1f4-8956-11e6-9faa-faaa7a92869d.png)

I try at chrome, firefox and diferent computers without sucess... my image size is the recomended:
![image](https://cloud.githubusercontent.com/assets/4204423/19039387/0f40a84a-8956-11e6-9cc3-2bb4d4ea669f.png)

Thz

**Comment by MarcusWasTaken** [comment]
I have the same error; I have tried with both .png and .svg files.
It seems like the site gets a 500 error if you try to use the demo image instead of uploading your own, and this is the message after you try to upload your own image and then try with the demo:

![image](https://cloud.githubusercontent.com/assets/10275026/19041844/0a7c35f2-898a-11e6-8397-142fb20cc08e.png)

And this is what the website alerts when I try to upload my own image:

![image](https://cloud.githubusercontent.com/assets/10275026/19041905/4c1367f6-898a-11e6-9a51-9bb0b42d56a1.png)

Hope that helps

**Comment by phbernard** [comment]
Thank you guys for reporting. Yep, there was a bug and it should be okay now. Do you confirm?

**Comment by MarcusWasTaken** [comment]
@phbernard works just fine for me now, thanks for the quick fix!

**Comment by kellerkichel** [comment]
@phbernard all Ok, thz
