### ISSUE TITLE
[Question] Should the HEAD code go on all pages, or just the homepage?

### ISSUE THREAD

**Issue by JHGrove3** [RealFaviconGenerator/realfavicongenerator#29]
Should the "HEAD" meta information about the file locations be placed on every page of the site, or just in the "HEAD" of the site the home page?

And if we place the meta information on every page, do we need to worry about the path from that page to the icons, or will the browser always start looking for the icons at the webroot?  

Alternatively, do we need to place the icon files in every subdirectory of the site so that they are always in the same directory as the page the viewer is looking at?

Thanks for your insight.

James Grove

**Comment by phbernard** [comment]
Hi,

Yes, you should add the code to every page, not just the homepage. Ideally, you have a dedicated mechanism for this, like a master template where the top-level `<html>... </html>` have been written once for all. In Rails, that would be a layout, but of course each technology comes with its own solution and names.

You don't have to worry about the paths, because they are absolute. For example, If you have chosen to place the files in root (default choice), then all paths are like `/apple-touch-icon-57x57.png` (note the leading `/`). So the browser will look for `apple-touch-icon-57x57.png` in the root of the web site, even if the current page is `/some/path/some_page.html`.

As a consequence, the answer to your last question is "no", you only have to copy the favicon files once, in the location you have chosen during the generation (so in the root directory by default).

Does this answer your questions?

Regards,
Philippe

**Comment by phbernard** [comment]
(note: If I get no feedback, I will consider this question as correctly answered and I will close it)

**Comment by JHGrove3** [comment]
Yes - that seems to be working for me.  Thanks for the help!

**Comment by phbernard** [comment]
You're welcome!

**Comment by nogweii** [comment]
Would you mind copying this answer to the FAQ? I wasn't sure myself.

Also, it seems like that could end up with a lot of additional weight to pages. I guess there is no `<link>` that says "go here to find all the icons information?", huh?. Bah.
