### ISSUE TITLE
cURL error 28: Connection timed out after 5000 milliseconds

### ISSUE THREAD

**Issue by pavlikus** [RealFaviconGenerator/realfavicongenerator#301]
An error occured: Cannot download JSON file at https://realfavicongenerator.net/files/93fe39047009e678835828267e0ada0f8e899cc4/json_result.json: cURL error 28: Connection timed out after 5000 milliseconds

**Comment by phbernard** [comment]
As far as I know, the service didn't have any glitch recently. So I'm tempted to blame the client :)

Did you use the WordPress plugin? If so, how is your WordPress site hosted? Did you try to generate the favicon once or several times?

**Comment by pavlikus** [comment]
WordPress 4.7.1
Favicon by RealFaviconGenerator Version 1.3.9
problem all time
hosting - https://www.fluccs.com.au/ - Australia

**Comment by phbernard** [comment]
Okay. I've just sent this:

"
Hi,

I'm the author of Favicon by RealFaviconGenerator, a puopular WordPress plugin (100,000+ active installs).

One of my user is facing an issue. This is because he cannot download assets from another site, and I suspect this is because of your WordPress hosting settings.

Could you please tell me if there is a limitation regarding CURL and timeouts? More of this here: https://github.com/RealFaviconGenerator/realfavicongenerator/issues/301

Regards,
Philippe
"
 Via this page: https://www.fluccs.com.au/contact-us/

**Comment by phbernard** [comment]
Staff answer (they replied very quickly, on a Synday; great!)

"
Hello Philippe,

Can you please have your client to open the ticket from our client area with the problem description and steps to replicate the problem.

We will further investigate the problem and provide the details to the client.

Regards
Shane - Support
Fluccs - The Australian Cloud
www.fluccs.com.au
"

@pavlikus, I advice you to contact their support and to indicate:

- The plugin name
- Copy/paste the last sentence (about CURL)
- The link to this issue

**Comment by pavlikus** [comment]
thank's. hoster fix problem
