### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by MrWrightAZ** [RealFaviconGenerator/realfavicongenerator#309]
Just installed on site. Received following error:

An error occured: Cannot download JSON file at https://realfavicongenerator.net/files/8e01a896e588e65178362f25343c48c52949951d/json_result.json: cURL error 51: SSL: certificate subject name 'api.realfavicongenerator.net' does not match target host name 'realfavicongenerator.net'

Suggestions?

**Comment by phbernard** [comment]
Thank you for reporting. The issue was also [reported as a plugin issue](https://wordpress.org/support/topic/error-51-cant-get-favicon-to-install/).

I couldn't reproduce the issue and everything I tried (online diagnosis tools, etc.) didn't provide any relevant information, which made the problem tougher than it should.

However, the certificate was updated a few minutes ago. That should fix the problem. Could you give it another try and report what happens now?

**Comment by MrWrightAZ** [comment]
I just tried it and it worked. Thank you.
