### ISSUE TITLE
Pinned app windows 10 ignores tile color from browserconfig.xml

### ISSUE THREAD

**Issue by geiregjo** [RealFaviconGenerator/realfavicongenerator#331]
I have a Windows Surface (tablet) running Windows 10. When I pin my website as a pinned application then the tile color configured in browserconfig.xml is ignored. Windows derives a tile color from the configured favicon.

This is not the case on a regular desktop running windows 10. I have no clue why it is ignoring it.

**Comment by ataylor32** [comment]
My browserconfig.xml file's `<TileColor>#abcdef</TileColor>` is honored when I use Internet Explorer 11 on Windows 8.1 to pin my site to the Start screen, but not when I use Edge on Windows 10 to pin my site to the Start menu. In order to get the tile color to work when using Edge on Windows 10 to pin my site to the Start menu, I have to use `<meta name="msapplication-TileColor" content="#abcdef">`. I am using:

Microsoft Edge 40.15063.0.0
Microsoft EdgeHTML 15.15063

**Comment by phbernard** [comment]
Thank you for reporting.

I realize that the [compatibility test](https://realfavicongenerator.net/favicon_compatibility_test) is not helpful as it is today. When you add the test page to the Start Menu, as the icon is not transparent, there is no way to check the browser behavior.

I updated the test and ran it on Windows 10 and Microsoft Edge 41.16299.15.0.

- browserconfig and no TileColor meta in the HTML. As you observed, the color is not taken into account:

![image](https://user-images.githubusercontent.com/423852/35336801-cf5f2368-0119-11e8-8316-4d2e76e52cf8.png)

Even more confusing, I don't know where this purple (#7f34ed) comes from (not declared in another file, not the mean of the colors of the icon...).

- TileColor meta in the HTML (and browserconfig unchanged). Again, as you observed:

![image](https://user-images.githubusercontent.com/423852/35336818-ddaa0ae6-0119-11e8-8087-5b3b3d1981cc.png)

Yellow is the color declared in the HTML TileColor meta.

Conclusion: `<meta name="msapplication-TileColor" content="#abcdef">` should always be generated.

**Comment by phbernard** [comment]
Deployed a minute ago.
