### ISSUE TITLE
Multiple errors. Probably conflicting with original setup..

### ISSUE THREAD

**Issue by Astebbi1** [RealFaviconGenerator/realfavicongenerator#332]
Thanks for the great plugin! It works on my personal site but not my company's.

I originally had manually set up a few icons so that could be the issue but here are the errors I'm getting with the checker.

> The high resolution Touch icon is absent
> There is no Touch icon
> 
> The high resolution icon is absent
> There is no icon for Android Chrome
> The Web App Manifest is absent
> 
> The mask icon for Safari pinned tabs is absent
> The mask icon has no color
> 
> **favicon.ico is available in the root of your web site
> There is an icon for classic browsers
> favicon.ico is present**
> Image https://valueprop.com/favicon.ico is ill-formed
> favicon.ico is missing some icons of recommended sizes (16x16, 32x32, 48x48)
> Cannot find https://icon.png
> favicon.ico does not contain the highest resolution icon (48x48)

I have tested on Android and the share to home screen icon does not show up, along with the app name. Hoping the way I tried to manually do this before didn't mess things up, do you know of any settings that would make this plugin incompatible with the site?

it's www.valueprop.com

Thanks again, plugin saved me a lot of time on my other website!

**Comment by DeanV255** [comment]
Hi Astebbi,

I noticed on your website you've now gotten this to work. Would you mind sharing what you've done? 
I've been trying for two days now to add this to my website and i have tried many things to resolve this even changing my images from 32bit down to 24bit that i thought was the issue, as it turns out ti's not and i am getting the same errors as yourself above. [Apologies for Necro too]

**Comment by phbernard** [comment]
@Astebbi1 Sorry I didn't investigate this one :(

@DeanV255 What is the URL of your site?

**Comment by DeanV255** [comment]
@phbernard 
Thank you for the reply on this. I believe i might actually know my issue now. My website is currently hosted on a Synology Web Server that points to my public IP. 

I have a domain purchased that masks the public and changes the name to [www.adamtrott.co.uk](http://adamtrott.co.uk)
I just changed the masking off (Because i could see the favicon if i opened up the index itself) and behold the favicon, now named myIcon for testing reasons, showed up. Reapplied the mask and it's gone so i believe that is my issue. Website as above, www.adamtrott.co.uk

```
<link rel="icon" href="myIcon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="http://mypublicip/myIcon.ico" type="image/x-icon" />
```
I have tried www.adamtrott.co.uk and my public ip in the link to push it but sadly it doesn't work. I spent all of yesterday assuming it was because my icon was 32bit, as it's turned out this is not the case, i just have DNS issues. I'm still fairly new to code apart from HTML and CSS, but when it comes to DNS im still learning with much to learn.

I'd really like to get my website to be www.adamtrott.co.uk rather than my PIP but still be on my Synology server, but sadly i just don't know how to.

**Comment by phbernard** [comment]
I can't see you favicon code... did you use RealFaviconGenerator?

**Comment by DeanV255** [comment]
I did yes, sorry i had removed it for testing purposes when i did the Mask removal. I have re-applied this now. 

Edit:
Even though i have used RFG, when i use your favicon checker it doesn't seem to see any of the icons even though i have put them in the correct folder and the code is point to them. That maybe resolved if i can resolve the fact it isn't picking up my main favicon though so don't worry about that too much.

```
    <link rel="apple-touch-icon" sizes="180x180" href="image/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="image/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="image/favicon-16x16.png">
    <link rel="manifest" href="image/site.webmanifest">
    <link rel="mask-icon" href="image/safari-pinned-tab.svg" color="#132873">
    <link rel="shortcut icon" href="image/favicon.ico">
    <meta name="msapplication-TileColor" content="#1c3861">
    <meta name="msapplication-config" content="image/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
```

**Comment by phbernard** [comment]
Well there are some issues, probably because you renamed the "img" directory to "images".

You can run the checker by changing the URL: https://realfavicongenerator.net/favicon_checker?protocol=http&site=[put your IP here]

**Comment by DeanV255** [comment]
I actually have a separate folder called 'image' i placed all the files into but just encase that is causing issues i have changed the code and moved them all into the root folder of the website.

Running the checker i get the same issue with them in the root too.

**Comment by DeanV255** [comment]
So i believe i fixed it. It was nothing to do with RFG as i expected but DNS issues on my side.

Again, I'm still learning DNS so my apologies for not exactly been able to articulate my problem. My DNS provider had a Forward with Mask option, this sounded perfect to me. Sadly this has been causing my issues and i didn't know a single way around it.

I have now created an "A" Record, adamtrott.co.uk to point at my PIP and that has resolved the issue, at the moment, i just wanted to drop you the message to let you know the favicon is now showing for me after doing this.

**Comment by phbernard** [comment]
Alright, I guess we can safely say RealFaviconGenerator is out of this business :)
