### ISSUE TITLE
Non-interactive API Generates Empty Zip folder

### ISSUE THREAD

**Issue by treefishuk** [RealFaviconGenerator/realfavicongenerator#366]
Posting the JSON below to the Non-Interactive API returns a JSON response with a link to a zip folder and success status. But the only thing in the zip is the read me file. No Icons or manifest included.  

I am unsure if there are required options (the documentation doesn't appear to suggest that), if I am doing something wrong or if the service is broken. 

I have tried:

- Base64 image and type as inline 
- Removing the settings section entirely 
- Different Images URLs

... None of which made any difference. 

Help would be greatly appreciated. 

```
{
    "favicon_generation":
    {
        "api_key":"<APIKEYHERE>",
        "master_picture":
        {
            "type": "url",
            "url":"https://placehold.it/300x300.png",
        },

        "settings":{
            "compression":"3",
            "scaling_algorithm":"Mitchell",
            "error_on_image_too_small":true,
            "readme_file":true,
            "html_code_file": false,
            "use_path_as_is":true
        }
    }
}
```

**Comment by phbernard** [comment]
This must be because you have no `design` section in the request, thus RFG considers that there are no platform to support... and generates nothing.

My advice: [visit RFG](https://realfavicongenerator.net/), start a favicon creation as a regular use and play with the options you want (particular design settings, icon path, etc.). On the result page, select the "RFG API" far right tab:

![image](https://user-images.githubusercontent.com/423852/36718818-623cf73e-1ba3-11e8-83c5-c14d37c9ccbc.png)

RFG gives you the corresponding non-interactive request. You can use this request as a reference or even the basis for your own client.

**Comment by treefishuk** [comment]
Fantastic. Thank you will do that, that's brilliant.
