### ISSUE TITLE
Pictures missing in favicon.ico

### ISSUE THREAD

**Issue by tonyash** [RealFaviconGenerator/realfavicongenerator#42]
Only 16x16 is being added to favicon.ico by realfavicongenerator. After using the site to generate my icons, I run the test and get the following results:

The favicon.ico file is present.
favicon.ico seems corrupted or not in ICO format.
Picture(s) contained in favicon.ico have correct dimensions.
Some picture(s) are missing in favicon.ico:

16x16 picture
32x32 picture
48x48 picture
Learn more

favicon.ico is declared in the HTML code. Although this is usually recommended, this is actually a bad thing. Learn more.

**Comment by phbernard** [comment]
Not good. Thank you for reporting. Is the site live, so I can check by myself? If you don't want to make  this information public, please mail me at philippe@realfavicongenerator.net

**Comment by phbernard** [comment]
(just to make the conversation consistent: you sent me the URL by email)

This is because a favicon is declared. Somewhere in the homepage, there is:

```
<link rel="shortcut icon" href="favicon-32x32.png" type="image/x-icon" />
```

This declaration is not part of the code generated by RealFaviconGenerator, is that right?

There are two isues with this declaration:
- This is a `favicon.ico` declaration, but it declares a PNG icon. This won't work on legacy browsers. This is why the checker complains.
- Because of the other declarations of RealFaviconGenerator, this declaration is quite counter-productive since it may "hide" the other PNG icons. This is also reported by the checker.

**Comment by tonyash** [comment]
it was a typo. my apologies for the false alarm...it's late here :(

On Tue, May 20, 2014 at 12:35 AM, Philippe Bernard <notifications@github.com

**Comment by phbernard** [comment]
No problem! You're welcome!
