### ISSUE TITLE
Social Generator Not Working

### ISSUE THREAD

**Issue by ghost** [RealFaviconGenerator/realfavicongenerator#439]
The social generator is working. It accepts all input and when the "Generate" button is pressed, the "working" screen comes up and never finishes. 

<img width="1127" alt="Your_generated_Facebook_metadata" src="https://user-images.githubusercontent.com/65671426/82837877-71390000-9e98-11ea-9e12-8b0c64b99033.png">

**Comment by jenewland1999** [comment]
I too have had the same issue. I have tested the following browsers (both not in and in private browsing mode - in case cache/cookies/sessions were having an effect):

- Chrome 83.0.4103.97
- Firefox 77.0.1

Looking at the developer console it appears there are a couple of resources which it fails to fetch because of either an Internal Server Error (500) or Forbidden (403). While this might not be the source of the issue I thought it might retain some relevance.

![image](https://user-images.githubusercontent.com/34895363/84565913-aed8cc80-ad64-11ea-826e-156c5c73f493.png)

**Comment by epexa** [comment]
#436 
#442

**Comment by phbernard** [comment]
Social generator is finally back. Alert system setup so I'm warned immediately when it happens again. Sorry for the long wait :(
