### ISSUE TITLE
Add crossorigin="use-credentials"

### ISSUE THREAD

**Issue by UweKeim** [RealFaviconGenerator/realfavicongenerator#474]
According to [this blog entry](https://medium.com/@aurelien.delogu/401-error-on-a-webmanifest-file-cb9e3678b9f3), the generated webmanifest link that currently looks like this:

```html
<link rel="manifest" href="/site.webmanifest">
```

Should look like this:

```html
<link rel="manifest" href="/site.webmanifest" crossorigin="use-credentials">
```

I.e. the `crossorigin="use-credentials"` attribute should be added.

I'm doing this successfully since quite a long time and it seems to work just pretty good.

### My suggestion

Please also include the `crossorigin="use-credentials"` attribute when generating the HTML fragment to insert into my HTML page.

**Comment by tigt** [comment]
I think this only happens if the manifest URL needs cookies/HTTP basic auth/etc. to be successfully fetched, right? At least, [that’s what MDN suggests](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin#example_webmanifest_with_credentials):

> The `use-credentials` value must be used when fetching a manifest that requires credentials, even if the file is from the same origin.

More background at https://github.com/w3c/manifest/issues/535

**Comment by UweKeim** [comment]
Not sure. In my case I did not need cookies and still the attribute was necessary. Adding it ever since with no negative effects.
