### ISSUE TITLE
browserconfig.xml not generating

### ISSUE THREAD

**Issue by onebitrocket** [RealFaviconGenerator/realfavicongenerator#6]
Hi

I've ran the generator in several browser on both mac and pc.
It appears that the browserconfig.xml file is not generating as part of the code.
it did randomly generate once over the weekend (07/12/2013?)

It might also be useful to adds in the <meta name="application-name" content="the tile name"/> in to the code

**Comment by phbernard** [comment]
After several attempts, I could not reproduce the bug.

However, browserconfig.xml is not always generated, depending of the location of the favicon files:
- If you choose "I will place favicon files at the root of my web site", browserconfig.xml is generated.
- If you choose "I cannot or I do not want to place favicon files at the root of my web site", browserconfig.xml is not generated. This is because this file is expected to be in the root directory, so it does not make sense in this scenario. And the Windows 8.1 icons are then declared in the HTML code itself, so the generated HTML is also impacted by this choice.

Could this explain your observations?

Else, could you share your favicon master picture, in order to reproduce the issue as accurately as possible?

**Comment by phbernard** [comment]
The issue was open a month ago and got no feedback since then. If there is no news, I will consider it as invalid and close it.

**Comment by onebitrocket** [comment]
Sorry, I can't replicate the issue.
I got the full code eventually though

Couple of questions though:

Could the ie markup be added inside a if ie statement? 
The following line comes up as invalid on w3
`<meta name="msapplication-square150x150logo" content="/mstile-150x150.png" />`

I also added in the following line
`<meta name="application-name" content="Website name"/>`
Are the images passed through some kind of optimisation process, such as tinypng?

Could the be some kind of subscribe to be kept up to date on changes, or a user account that monitors a users sites?

Thanks for this it's a great tool, really useful.

**Comment by phbernard** [comment]
No problem! Thank you for closing the issue.

Validation: Good point. This must be tested, something I won't do right now. So I opened https://github.com/phbernard/realfavicongenerator/issues/12 just for this.

application-name: Yes, it is useful to add this markup. Yet this feature has no equivalent on other platforms: Android and iOS take the page's title and let the user change it when he creates a link on the home screen. So does IE11 when this markup is not present. So I deliberately chose to ignore this markup.

Optimization: The pictures compression feature was added a few weeks ago. It is optional. It relies on pngquant, which is apparently the tool used by TinyPNG. Plus it's free.

Changes: All changes in the generated code and pictures are announced on Twitter, Google Plus and Facebook. They are tracked here: http://realfavicongenerator.net/change_log .
