### ISSUE TITLE
Google Chrome now recommends 192x192

### ISSUE THREAD

**Issue by mietek** [RealFaviconGenerator/realfavicongenerator#77]
The Google Chrome recommendation of a 196x196 icon is no longer current, as it's been changed to 192x192 sometime between [6 July](http://web.archive.org/web/20140706172411/https://developer.chrome.com/multidevice/android/installtohomescreen#icon) and [today](https://developer.chrome.com/multidevice/android/installtohomescreen#icon).

**Comment by phbernard** [comment]
Thank you for reporting. I noticed this a few days ago, when I started an article I first titled "Android Chrome and the 196x196 icon dilemma"... which I changed an hour later when I red Android Chrome specs again :)

If you don't mind, I make this issue a duplicate of #26. It is not strictly a duplicate, but this issue is the origin of a larger revamping and issue #77 will be fixed at the same time.

**Comment by mietek** [comment]
Sure. Thank you for your service.

**Comment by phbernard** [comment]
Fixed!
