### ISSUE TITLE
Chrome now recommends 192x192 not 196x196

### ISSUE THREAD

**Issue by mcummins** [RealFaviconGenerator/realfavicongenerator#81]
The advice seems to have changed. At this link:
https://developer.chrome.com/multidevice/android/installtohomescreen

> link rel="icon" sizes="192x192" href="nice-highres.png" (recommended)
> link rel="icon" sizes="128x128" href="niceicon.png"
> 
> Caution:The 192px image format is recommended. The last two formats (apple-touch-*) are deprecated, >and will be supported only for a short time.

So favicon-196x196.png seems to be out of date and 128 is missing.

**Comment by phbernard** [comment]
Thanks for reporting!

That's right, the 196x196 icon was replaced a few weeks ago by a new 192x192 icon. Apparently, <a href="http://realfavicongenerator.net/blog/android-chrome-and-its-favicon/">Chrome takes the highest resolution icon below or equal to 192x192</a>, so the 128x128 icon is not necessary. Plus, since v36, it does not consider the Apple Touch icon as soon as there is a suitable PNG icon.

This will be addressed as part of issue #26, although that was not its original purpose. To be deployed soon, I hope during the weekend.

**Comment by phbernard** [comment]
A weekend and three days later... Fixed!
